### ISSUE TITLE
Suggestion) Why don't we make fibo.py

### ISSUE THREAD

**Issue by JuGiGyeong** [JuGiGyeong/branch-practice#1]
Fibonacci Sequence를 구하는 파이썬 스크립트를 만들고 싶어요
만들어 주실꺼죠??? (찡긋)

## Tasks

- [ ] Fibo with Recursion
- [ ] Fibo with Memoization
- [ ] Fibo with binet's formula

$$F_n=\dfrac{\left(\dfrac{1+\sqrt{5}}{2}\right)^n-\left(\dfrac{1-\sqrt{5}}{2}\right)^n}{\sqrt{5}}$$
